### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by mr-tron** [gliheng/flutter-app-template#6]
I think the best license will be `Apache 2` because it allows to make application based on this template under any over license.

**Comment by gliheng** [comment]
Hi, I'm not an expert on licenses. The original flutter-rs project used MIT. It's completely arbitrary though.  So MIT or apache, what's the differences?

**Comment by mr-tron** [comment]
You can think about Apache 2 like about improved MIT. It protects users from patent trolling.
MIT and Apache2 are completely compatible.

**Comment by mr-tron** [comment]
So you can use MIT for both projects, if you want.  It`s ok.

**Comment by gliheng** [comment]
OK, let's keep it consistent using MIT for now. Can you change your PR too?

**Comment by mr-tron** [comment]
done
